### ISSUE TITLE
Mod Request: Alternate Current

### ISSUE THREAD

**Issue by mr-pi12** [zorroware/fabric-optimization-mods#42]
**Requirements for a mod to be added:**
1. The mod must be open-source.
2. The mod cannot sacrifice vanilla behavior for performance.
3. The mod must be actively maintained.

**Mod name:** Alternate Current

**Type of mod (e.g. rendering, lighting, extra):** other

**Repository (e.g. GitHub, GitLab, Gitea):** https://github.com/SpaceWalkerRS/alternate-current

**Developer/organization:** SpaceWalkerRS

**Additional notes:**
Adds redstone update optimizations

Tries to maintain vanilla parity, while improving performance, likely most effective with large redstone machines

**Comment by DragonEggBedrockBreaking** [comment]
You are incorrect, this mod does not try to maintain vanilla a parity. It explicitly patches locational contraptions as a mod feature, meaning that any locational vanilla contraptions will not work

**Comment by mr-pi12** [comment]
It doesn't? That's disaopointing.

**Comment by DragonEggBedrockBreaking** [comment]
For many years people have been trying to optimise red stone dust while keeping vanilla parity, e.g. carpet mod, lithium, etc. But all of them have realised that it is basically impossible, especially when the code changes every update, making it in feasible to maintain this impossible code. SpaceWalker went into this project explicitly breaking vanilla parity, because he knew that some people wouldn’t care about non-vanilla parity and this is better than nothing. He essentially rewrote red stone dust while making it more optimised and non-locational

**Comment by mr-pi12** [comment]
Yeah, that would explain the lack of redstone optimization mods that keep vanilla mechanics. Thanks for telling me :)
